import time
from sys import exit
import cv2
from kafka import KafkaProducer
from os import path

topic = "HoangPhuc-distributed-video1"
kafka_server = "kafka:9092"


def publish_video(video_file):
    """
    Publish given video file to a specified Kafka topic. 
    Kafka Server is expected to be running on the localhost. Not partitioned.
    
    :param video_file: path to video file <string>
    """
    # Start up producer
    producer = KafkaProducer(
    bootstrap_servers=kafka_server,
    acks='all',
    linger_ms=10,
    retries=3,
    value_serializer=lambda v: v
)


    # Open file
    video = cv2.VideoCapture(video_file)
    
    print('publishing video...')

    while(video.isOpened()):
        print("This code is set up by Le Nguyen Hoang Phuc - 23521198")
        success, frame = video.read()

        # Ensure file was read successfully
        if not success:
            print("bad read!")
            break
        h, w, _ = frame.shape
        position = (10,h - 20)

        cv2.putText(frame, "This code is generated by Le Nguyen Hoang Phuc - 23521198",
                    position,
                    cv2.FONT_HERSHEY_SIMPLEX,
                    1,
                    (0,255,255),
                    2,
                    cv2.LINE_AA) # Convert image to png

        ret, buffer = cv2.imencode('.jpg', frame)

        # Convert to bytes and send to kafka
        producer.send(topic, buffer.tobytes())
        producer.flush()

        time.sleep(0.2)
    video.release()
    print('publish complete')
try:
    video_path="/video/video.MOV"
    try:
        if (not path.exists(video_path)):
            raise FileNotFoundError(f"Video file not fount: {video_path}")
    except FileExistsError as e:
        print(e)    
        exit(-1)
    publish_video(video_path)
except KeyboardInterrupt:
    print("Break\n")
    print("Live ended...")